# Generated by Django 3.2.14 on 2022-08-01 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('n_cadastur', models.IntegerField(verbose_name='Nº do Cadastur')),
                ('telefone', models.CharField(max_length=11)),
                ('n_total_uh', models.IntegerField(verbose_name='Nº total de UH')),
                ('n_total_leitos', models.IntegerField(verbose_name='Nº total de Leitos')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
            ],
            options={
                'ordering': ['regiao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_uh_ocupados', models.IntegerField(verbose_name='Nº UH ocupados')),
                ('n_leitos_ocupados', models.IntegerField(verbose_name='Nº Leitos ocupados')),
                ('obs', models.CharField(max_length=150, verbose_name='Observação')),
                ('dt_1', models.DateField(verbose_name='Data inicial')),
                ('dt_2', models.DateField(verbose_name='Data final')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Dt. Inclusão')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocupacao.hospedagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hospedagem'],
            },
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocupacao.regiao', verbose_name='Região'),
        ),
        migrations.AddField(
            model_name='hospedagem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
